### ISSUE TITLE
Automation mit Dingz buton

### ISSUE THREAD

**Issue by muffbernard** [sofa74surfer/homeassistant#1]
Zuerst mal danke für die Integration von Dingz, es war ein grosse Hilfe, denn das YAML ist komplett neu für mich. Ich möchte gerne wenn ich den Knopf oben links von meinem DINGZ schalte Ich einen Script von HomAssistant einschalte. Könnt ihr mir da weiter helfen?

**Comment by sofa74surfer** [comment]
Hallo @muffbernard 
Das ist mein persönliches GIT Repository und kein Support Forum. Das heisst in diesem Repository bin nur ich und keine Community am Werk und damit ist das auch keine offizielle Integration von Dingz.

Hilfe der Community findest du grundsätzlich hier https://community.home-assistant.io/ oder hier https://forum.dingz.ch/

Um ein Script von einem Dingz Taster aufzurufen machst du folgendes: 
1. Eine Automation in HA mit Webhook als Trigger
2. In der Automation rufst du das Script auf
3. Auf deiner Dingz Taste hinterlegst du den Webhook (z.B. put://[ip]:[port]/api/webhook/[name]), wobei [ip]/[port] dein HA Server sind und [name] dein Name des Webhook Trigger in der Automation

en Gruess, Stephan
