### ISSUE TITLE
SurePetcare

### ISSUE THREAD

**Issue by sgrasser** [sofa74surfer/homeassistant#2]
Hey, finde Dein Projekt spannend, bin selbst an etwas ähnlichem. Mich hätte Interessiert, wie du SurePetcare integriert hast in HA um zu signalisieren, wenn die Katze durch die Klappe geht.
Merci Simon

**Comment by sofa74surfer** [comment]
Hoi Simon
Das geht über die Standard Integration Sure Petcare. Die erstellt dir dann entsprechende Geräte für den Hub, Napf, Katzentüre und deine Katzen. Die Katze hat den Status abwesend, wenn sie raus ging und anwesend, wenn sie daheim ist. Den Status-Wechsel kannst du dann in einer Automation abfangen.
en Gruess
Stephan
